language: cpp
arch:
  - amd64
  - arm64
os:
  - linux
  - osx
compiler:
  - clang
  - gcc
script:
  - make vars
  - DEBUG=1 make vars
  - make test/stl
  - ASAN_OPTIONS=detect_leaks=0 make test/ci
notifications:
  email: false
after_success:
  - bash <(curl -s https://codecov.io/bash)
